### PR TITLE
small change

### PR DESCRIPTION
**Pull request by macox**
Signed-off-by: Mark Cox <markcox20@hotmail.com>

### CODE REVIEW

**Comment by macox** [comment]
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:
To fully approve this pull request, please assign additional approvers.
We suggest the following additional approver: **macox**

If they are not already assigned, you can assign the PR to them by writing `/assign @macox` in a comment when ready.

The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=macox%2Fmy-cool-app).

The pull request process is described [here](https://git.k8s.io/community/contributors/guide/owners.md#the-code-review-process)

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/macox/my-cool-app/blob/master/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>

**Comment by macox** [comment]
:star: PR built and available in a preview environment **macox-my-cool-app-pr-1** [here](http://my-cool-app.jx-macox-my-cool-app-pr-1.35.246.109.5.nip.io)

**Comment by macox** [comment]
:star: PR built and available in a preview environment **macox-my-cool-app-pr-1** [here](http://my-cool-app.jx-macox-my-cool-app-pr-1.35.246.109.5.nip.io)

**Comment by macox** [comment]
:star: PR built and available in a preview environment **macox-my-cool-app-pr-1** [here](http://my-cool-app.jx-macox-my-cool-app-pr-1.35.246.109.5.nip.io)

**Comment by edwardmlyte** [comment]
Great work @macox

**Pull request merged**
